#Create Custom Container Image
#Push to DockerHub Registry
---
- hosts: localhost
  tasks: 
  - name: Pull .war artifact from Artifactory
    become: true
    become_user: root
    get_url:
      url: https://valaxytech529.jfrog.io/artifactory/vivo-libs-release-local/com/antrix/antrix/1.1-RELEASE/antrix-1.1-RELEASE.war
      dest: .
      url_username: "rohan.reddy529@gmail.com"
      url_password: "4getmenot@J"

  - name: Rename .war Artifact
    command: mv antrix-1.1-RELEASE.war antrix.war
  
  - name: Build image and with build args
    docker_image:
      name: antrix
      build:
        path: .
        pull: no
        args:
          listen_port: 8080
      source: build

  - name: Log into DockerHub
    docker_login:
     username: rohan4linux
     password: Devops@1409

    
  - name: Push to docker hub
    docker_image:
      name: antrix
      repository: docker.io/rohan4linux/antrix:1.0
      push: yes
      source: local
