#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iwayq-deploy
  namespace: prod
  labels:
    app: iwayq-app
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: iwayq-app
  template:
    metadata:
      labels:
        app: iwayq-app
    spec:
      containers:
      - name: iwayq-container
        image: docker.io/rohan4linux/iwayq:1.0
        ports:
        - containerPort: 8080